name: Test and Docker Deploy
run-name: ${{ github.actor }} is testing project
on: 
  push:
    branches:
      - '*'
      - '!main'
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests/

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:test